version: 2

updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 20
    directories: |
      - "/application"
      - "/.github/actions/**/"
    versioning-strategy: increase
    schedule:
      interval: "weekly"
    groups:
      npm-development-dependencies:
        dependency-type: "development"
      npm-docusaurus-dependencies:
        patterns:
          - "@docusaurus/*"
          - "react"
          - "react-*"
          - "@mdx-js/react"
          - "clsx"
          - "prism-react-renderer"

  - package-ecosystem: github-actions
    open-pull-requests-limit: 20
    directories:
      - "/"
      - "/.github/actions/**/action.yml"
    schedule:
      interval: weekly
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "devcontainers"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "docker"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-dependencies:
        patterns:
          - "*"
