name: Generate Documentation
description: |
  Generate project metadata pages

  Features:

  - Scans all repositories in the organization
  - Categorizes projects by type
  - Generates the projects overview page
  - Updates homepage with featured projects

inputs:
  github-token:
    description: GitHub token used to authenticate repository queries.
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js and install dependencies
      uses: hoverkraft-tech/ci-github-nodejs/actions/setup-node@6809332ced7647b3d52300a47d65657283f3395e # 0.16.0
      with:
        working-directory: ${{ github.action_path }}

    - name: Generate documentation from repositories
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        TEMPLATE_NAME: ${{ inputs.template-name }}
        NODE_PATH: ${{ github.action_path }}/node_modules
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const { run } = require('${{ github.action_path }}/generate-docs.js');
          await run({ github });
