name: Generate Documentation
description: |
  Generate project metadata pages

  Features:

  - Scans all repositories in the organization
  - Categorizes projects by type
  - Generates the projects overview page
  - Updates homepage with featured projects

inputs:
  github-token:
    description: GitHub token used to authenticate repository queries.
    required: true

runs:
  using: composite
  steps:
    - name: Generate documentation from repositories
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const { run } = require('${{ github.action_path }}/generate-docs.js');
          await run({ github });
