name: Common Continuous Integration tasks

on:
  workflow_call:
    outputs:
      build-artifact-id:
        description: "The build artifact id."
        value: ${{ jobs.continuous-integration.outputs.build-artifact-id }}
    secrets:
      ALGOLIA_API_KEY:
        required: true

permissions: {}

jobs:
  linter:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/linter.yml@7034f6ae5bae1ec46a0108e8efb60d102e88961d # 0.37.2
    permissions:
      actions: read
      contents: read
      issues: write
      packages: read
      pull-requests: write
      security-events: write
      statuses: write

  continuous-integration-prepare-docs:
    uses: hoverkraft-tech/ci-github-nodejs/.github/workflows/continuous-integration.yml@df348077afa4e79725151d50606e9dc63f86dcb6 # 0.24.4
    strategy:
      matrix:
        working-directory:
          - .github/actions/prepare-docs
          - .github/actions/generate-docs
          - .github/actions/inject-docs
          - .github/actions/resolve-docs-target
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: write
      security-events: write
    with:
      working-directory: ${{ matrix.working-directory }}
      build: null
      lint: null
      dependency-review: false

  continuous-integration:
    uses: hoverkraft-tech/ci-github-nodejs/.github/workflows/continuous-integration.yml@df348077afa4e79725151d50606e9dc63f86dcb6 # 0.24.4
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: write
      security-events: write
    secrets:
      build-secrets: |
        ALGOLIA_API_KEY=${{ secrets.ALGOLIA_API_KEY }}
    with:
      working-directory: application
      build: |
        {
          "artifact": ["build"],
          "env": { "ALGOLIA_APP_ID": "${{ vars.ALGOLIA_APP_ID }}" }
        }
